### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Adau** [mjarmoc/nunjucks-brunch-static#1]
Why does the Nunjucks files have to be written with `< >` instead of `{ }` like in the official documentation? Can we overwrite it?

https://github.com/mjarmoc/nunjucks-brunch-static/blob/3857493eee4e3bde157f4b7bf074a629cbc8fefb/index.js#L6-L13

**Comment by mjarmoc** [comment]
@Adau it is because `{}` tags are reserved for nunjucks-brunch-static mechanisms.  For example `  {{>_partial}}`. I had to change the tags to avoid conflicts. Brunch has to distinguish brunch-static tags from nunjucks.
